
CREATE DATABASE [ChatBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ChatBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.JONAEXPRESS\MSSQL\DATA\ChatBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ChatBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.JONAEXPRESS\MSSQL\DATA\ChatBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ChatBD] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ChatBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ChatBD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ChatBD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ChatBD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ChatBD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ChatBD] SET ARITHABORT OFF 
GO
ALTER DATABASE [ChatBD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ChatBD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ChatBD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ChatBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ChatBD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ChatBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ChatBD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ChatBD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ChatBD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ChatBD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ChatBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ChatBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ChatBD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ChatBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ChatBD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ChatBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ChatBD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ChatBD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ChatBD] SET  MULTI_USER 
GO
ALTER DATABASE [ChatBD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ChatBD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ChatBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ChatBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ChatBD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ChatBD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ChatBD] SET QUERY_STORE = ON
GO
ALTER DATABASE [ChatBD] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ChatBD]
GO
/****** Object:  Table [dbo].[Groups]    Script Date: 21/02/2025 18:40:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Groups](
	[GroupId] [uniqueidentifier] NOT NULL,
	[GroupName] [nvarchar](50) NOT NULL,
	[CreatedBy] [uniqueidentifier] NOT NULL,
	[CreatedAt] [datetime] NULL,
	[ImageUrl] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[GroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Messages]    Script Date: 21/02/2025 18:40:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Messages](
	[MessageId] [uniqueidentifier] NOT NULL,
	[UserId] [uniqueidentifier] NOT NULL,
	[GroupId] [uniqueidentifier] NULL,
	[Content] [nvarchar](max) NOT NULL,
	[SentAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[MessageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 21/02/2025 18:40:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RoleId] [int] IDENTITY(1,1) NOT NULL,
	[RoleValue] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_RoleValue] UNIQUE NONCLUSTERED 
(
	[RoleValue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserGroups]    Script Date: 21/02/2025 18:40:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserGroups](
	[UserId] [uniqueidentifier] NOT NULL,
	[GroupId] [uniqueidentifier] NOT NULL,
	[RoleInGroup] [nvarchar](50) NULL,
	[JoinedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[GroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 21/02/2025 18:40:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [uniqueidentifier] NOT NULL,
	[user] [nvarchar](50) NOT NULL,
	[email] [nvarchar](100) NOT NULL,
	[password] [nvarchar](256) NOT NULL,
	[RoleId] [int] NOT NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Groups] ADD  DEFAULT (newid()) FOR [GroupId]
GO
ALTER TABLE [dbo].[Groups] ADD  DEFAULT (getdate()) FOR [CreatedAt]
G
ALTER TABLE [dbo].[Messages] ADD  DEFAULT (newid()) FOR [MessageId]
GO
ALTER TABLE [dbo].[Messages] ADD  DEFAULT (getdate()) FOR [SentAt]
GO
ALTER TABLE [dbo].[UserGroups] ADD  DEFAULT (getdate()) FOR [JoinedAt]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (newid()) FOR [UserId]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Groups]  WITH CHECK ADD FOREIGN KEY([CreatedBy])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Messages]  WITH CHECK ADD FOREIGN KEY([GroupId])
REFERENCES [dbo].[Groups] ([GroupId])
GO
ALTER TABLE [dbo].[Messages]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[UserGroups]  WITH CHECK ADD FOREIGN KEY([GroupId])
REFERENCES [dbo].[Groups] ([GroupId])
GO
ALTER TABLE [dbo].[UserGroups]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[UserGroups]  WITH CHECK ADD  CONSTRAINT [FK_UserGroups_RoleInGroup] FOREIGN KEY([RoleInGroup])
REFERENCES [dbo].[Roles] ([RoleValue])
GO
ALTER TABLE [dbo].[UserGroups] CHECK CONSTRAINT [FK_UserGroups_RoleInGroup]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([RoleId])
REFERENCES [dbo].[Roles] ([RoleId])
GO
USE [master]
GO
ALTER DATABASE [ChatBD] SET  READ_WRITE 
GO



--INSERTS
SET IDENTITY_INSERT Roles ON;

INSERT INTO Roles (RoleId, RoleValue) 
VALUES 
  (0, 'Usuari-normal'),
  (1, 'Administrador');

SET IDENTITY_INSERT Roles OFF;

--UPDATES

    UPDATE Groups
SET imageUrl = '6227A117-8658-488A-92B3-0332CDD71429.png'
WHERE GroupId = '6227A117-8658-488A-92B3-0332CDD71429';

UPDATE Groups
SET imageUrl = '957C8700-3C6F-4A56-8120-1DD09BFED4D1.png'
WHERE GroupId = '957C8700-3C6F-4A56-8120-1DD09BFED4D1';

UPDATE Groups
SET imageUrl = 'F9E89E2B-C27D-4CA8-A033-38BFC3877C7B.png'
WHERE GroupId = 'F9E89E2B-C27D-4CA8-A033-38BFC3877C7B';

UPDATE Groups
SET imageUrl = '8BFD8E28-A9CC-49FA-9E2A-6878CE16193E.png'
WHERE GroupId = '8BFD8E28-A9CC-49FA-9E2A-6878CE16193E';

UPDATE Groups
SET imageUrl = 'E853577D-837E-45F6-83A8-7BF20B262029.png'
WHERE GroupId = 'E853577D-837E-45F6-83A8-7BF20B262029';